<?php
declare(strict_types=1);

function render_staff(): void {
    $filter = is_string($_GET['status'] ?? null) ? $_GET['status'] : 'active';
    $allowed = ['active','received','preparing','ready','collected','cancelled'];
    if (!in_array($filter,$allowed,true)) $filter='active';
    $sql = $filter==='active' ? "status IN ('received','preparing','ready')" : 'status=?';
    $orders = query("SELECT * FROM orders WHERE $sql ORDER BY pickup_at,id LIMIT 100", $filter==='active'?[]:[$filter])->fetchAll();
    $counts = query("SELECT SUM(status='received') AS received,SUM(status='preparing') AS preparing,SUM(status='ready') AS ready FROM orders")->fetch();
    heading('THE STAFF DESK','Good service starts here.','Keep the counter moving. Check collection times and names before handing over.'); ?>
    <div class="staff-toolbar"><div class="stats"><?php foreach (['received'=>'Incoming','preparing'=>'In preparation','ready'=>'Ready to collect'] as $key=>$label): ?><div><strong><?= (int)$counts[$key] ?></strong><span><?= e($label) ?></span></div><?php endforeach; ?></div><div class="actions"><a class="button secondary" href="<?= e(url('staff',['status'=>$filter])) ?>">Refresh queue ↻</a><a class="button" href="<?= e(url('manage')) ?>">Manage menu ↗</a></div></div><nav class="filters staff-filters" aria-label="Order status"><?php foreach ($allowed as $value): ?><a class="filter <?= $value===$filter?'active':'' ?>" href="<?= e(url('staff',['status'=>$value])) ?>"><?= ucfirst($value) ?></a><?php endforeach; ?></nav>
    <div class="queue-grid"><?php foreach ($orders as $order): ?><article class="queue-card panel"><div class="queue-top"><span class="eyebrow"><?= e($order['reference']) ?></span><span class="badge <?= e($order['status']) ?>"><?= e(status_label($order['status'])) ?></span></div><h2><?= e($order['customer_name']) ?></h2><p class="queue-time"><?= e((new DateTimeImmutable($order['pickup_at']))->format('D j M · g:i a')) ?></p><small><?= e($order['phone']) ?><?= $order['group_name']?' · '.e($order['group_name']):'' ?></small><ul class="queue-items"><?php foreach (query('SELECT * FROM order_items WHERE order_id=?',[$order['id']])->fetchAll() as $item): ?><li><strong><?= $item['quantity'] ?> × <?= e($item['item_name']) ?></strong><?php if ($item['recipient']): ?><small>For <?= e($item['recipient']) ?></small><?php endif; ?><?php if ($item['instructions']): ?><small><?= e($item['instructions']) ?></small><?php endif; ?></li><?php endforeach; ?></ul><?php if ($order['notes']): ?><p class="order-note">Note: <?= e($order['notes']) ?></p><?php endif; ?><div class="queue-bottom"><strong><?= money((int)$order['total_cents']) ?></strong><small><?= $order['status']==='cancelled'?'Simulated refund':'Simulated payment' ?></small></div><div class="actions"><?php foreach (next_statuses($order['status']) as $next): ?><form method="post" <?= $next==='cancelled'?'data-confirm="Cancel this order and record a simulated refund?"':'' ?>><?= csrf_field() ?><input type="hidden" name="action" value="order_status"><input type="hidden" name="order_id" value="<?= $order['id'] ?>"><input type="hidden" name="status" value="<?= $next ?>"><button class="button <?= $next==='cancelled'?'secondary danger':'' ?>"><?= e(match($next){'preparing'=>'Start preparing','ready'=>'Mark ready','collected'=>'Mark collected','cancelled'=>'Cancel'}) ?></button></form><?php endforeach; ?></div></article><?php endforeach; ?></div><?php if (!$orders): ?><div class="empty panel"><h2>A clear counter.</h2><p>No orders in this view. Refresh to check for new arrivals.</p></div><?php endif;
}
function render_manage(): void {
    heading('KEEP IT FRESH','Your menu, your way.','Update prices, descriptions and availability. Existing receipts keep their original prices.'); ?><a class="underlined" href="<?= e(url('staff')) ?>">← Back to the queue</a><div class="manage-grid"><?php foreach (query('SELECT * FROM menu_items ORDER BY id')->fetchAll() as $item): ?><form method="post" class="panel"><?= csrf_field() ?><input type="hidden" name="action" value="menu_save"><input type="hidden" name="item_id" value="<?= $item['id'] ?>"><label>Item name<input name="name" value="<?= e($item['name']) ?>" maxlength="100" required></label><div class="field-grid"><label>Price (AUD)<input name="price" type="number" min="0.01" max="999.99" step="0.01" value="<?= number_format((int)$item['price_cents']/100,2,'.','') ?>" required></label><label>Category<select name="category"><?php foreach (['Coffee','Cold drinks','Bakery','Kitchen'] as $category): ?><option <?= $category===$item['category']?'selected':'' ?>><?= e($category) ?></option><?php endforeach; ?></select></label></div><label>Description<textarea name="description" maxlength="500" required><?= e($item['description']) ?></textarea></label><label>Allergens<input name="allergens" maxlength="190" value="<?= e($item['allergens']) ?>"></label><label class="checkbox"><input type="checkbox" name="available" <?= $item['available']?'checked':'' ?>><span>Available to order</span></label><button class="button secondary full">Save item</button></form><?php endforeach; ?></div><?php
}
