<?php
declare(strict_types=1);
require __DIR__ . '/staff_views.php';
function heading(string $eyebrow, string $title, string $description = ''): void { ?>
<div class="page-heading"><span class="eyebrow"><?= e($eyebrow) ?></span><h1><?= e($title) ?></h1><?php if ($description): ?><p><?= e($description) ?></p><?php endif; ?></div>
<?php }
function artwork(array $item, string $class = ''): void { ?><div class="food-art <?= e($item['artwork']) ?> <?= e($class) ?>" role="img" aria-label="Illustration of <?= e($item['name']) ?>"><span class="plate"><span class="food-shape"></span></span><span class="art-caption">FOLKS & CO.</span></div><?php }
function render_page(string $page, ?array $user): void {
    switch ($page) {
    case 'home': ?>
        <section class="hero"><div class="hero-copy"><span class="eyebrow"><span class="tiny-star">✳</span> A LITTLE LOCAL GOODNESS</span><h1>Your daily pause.<br>A little <em>better.</em></h1><p>Proper coffee, something fresh, and a moment for you. Order ahead. We’ll have the good stuff ready.</p><a class="button" href="<?= e(url('menu')) ?>">Find your favourite <span aria-hidden="true">↗</span></a><div class="hero-note"><span class="mini-cup" aria-hidden="true">☕</span><span>Made with care.<br><strong>Ready when you are.</strong></span></div></div><div class="hero-art"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="hero-stamp">BREWED<br>FOR YOUR<br><em>everyday.</em></div><div class="coffee-shadow"></div><div class="hero-saucer"><div class="hero-cup"><div class="coffee-surface"><span class="latte-leaf"></span></div></div></div><span class="hero-art-label">A GOOD DAY STARTS WITH A GOOD CUP.</span><span class="bean bean-one"></span><span class="bean bean-two"></span></div></section>
        <div class="values-strip"><span>Freshly made, always</span><b>✳</b><span>Skip the queue</span><b>✳</b><span>A little something for everyone</span><b>✳</b><span>Collect with a smile</span></div>
        <section class="section"><div class="section-heading"><div><span class="eyebrow">THE USUALS, FOR A REASON</span><h2>Meet your new regulars.</h2></div><a class="underlined" href="<?= e(url('menu')) ?>">Explore the menu ↗</a></div><div class="featured-grid"><?php foreach (query('SELECT * FROM menu_items WHERE available=1 ORDER BY id LIMIT 3')->fetchAll() as $item): ?><a class="featured-card" href="<?= e(url('menu', ['category'=>$item['category']])) ?>"><?php artwork($item); ?><div><h3><?= e($item['name']) ?></h3><span><?= money((int)$item['price_cents']) ?></span></div><p><?= e($item['description']) ?></p></a><?php endforeach; ?></div></section>
        <section class="how-section"><div><span class="eyebrow">LESS WAITING. MORE LIVING.</span><h2>Your coffee break,<br>on your terms.</h2><p>Flying solo or doing the office coffee run?<br>We’ll take care of the whole order.</p></div><ol class="steps"><li><span>01</span><div><h3>Pick your favourites</h3><p>A coffee, a bite, or a little of both. Add a name to each item for group orders.</p></div></li><li><span>02</span><div><h3>Make it your time</h3><p>Choose a collection slot and complete the demonstration checkout.</p></div></li><li><span>03</span><div><h3>Pop in. Pick up. Enjoy.</h3><p>Track your order, then collect when it’s ready. Simple as that.</p></div></li></ol></section>
    <?php break;
    case 'menu':
        $category = is_string($_GET['category'] ?? null) ? $_GET['category'] : '';
        $search = is_string($_GET['q'] ?? null) ? substr($_GET['q'],0,100) : '';
        $items = query('SELECT * FROM menu_items WHERE (? = \'\' OR category=?) AND (name LIKE ? OR description LIKE ?) ORDER BY id', [$category,$category,'%'.$search.'%','%'.$search.'%'])->fetchAll();
        heading('FRESH FROM OUR COUNTER','Something good is brewing.','Your favourites, made to order. All prices in AUD.'); ?>
        <div class="menu-toolbar"><nav class="filters" aria-label="Menu categories"><?php foreach ([''=>'All the good stuff','Coffee'=>'Coffee','Cold drinks'=>'Cold drinks','Bakery'=>'Bakery','Kitchen'=>'Kitchen'] as $value=>$label): ?><a class="filter <?= $category===$value?'active':'' ?>" href="<?= e(url('menu',['category'=>$value,'q'=>$search])) ?>" <?= $category===$value?'aria-current="true"':'' ?>><?= e($label) ?></a><?php endforeach; ?></nav><form class="search" method="get"><input type="hidden" name="page" value="menu"><input type="hidden" name="category" value="<?= e($category) ?>"><label class="sr-only" for="menu-search">Search the menu</label><input id="menu-search" name="q" value="<?= e($search) ?>" placeholder="Find your favourite…"><button aria-label="Search menu">↗</button></form></div>
        <div class="menu-grid"><?php foreach ($items as $item): ?><article class="menu-card"><?php artwork($item); ?><div class="menu-card-body"><div class="item-title"><h2><?= e($item['name']) ?></h2><strong><?= money((int)$item['price_cents']) ?></strong></div><p><?= e($item['description']) ?></p><small class="allergens"><?= $item['allergens']?'Contains: '.e($item['allergens']):'Ask us about dietary requirements' ?></small><?php if ($item['available']): ?><form method="post" class="add-form"><?= csrf_field() ?><input type="hidden" name="action" value="add_cart"><input type="hidden" name="item_id" value="<?= $item['id'] ?>"><details><summary>Make it yours / group order</summary><label>Who is it for? <input name="recipient" maxlength="60" placeholder="Optional name"></label><label>Preparation note <input name="instructions" maxlength="160" placeholder="e.g. no sugar"></label><small>For allergies, speak to staff before ordering. Substitutions are subject to availability.</small></details><div class="add-row"><label class="sr-only" for="qty-<?= $item['id'] ?>">Quantity for <?= e($item['name']) ?></label><input id="qty-<?= $item['id'] ?>" aria-label="Quantity for <?= e($item['name']) ?>" type="number" name="quantity" min="1" max="20" value="1" required><button class="button secondary">Add to bag <span aria-hidden="true">+</span></button></div></form><?php else: ?><div class="sold-out">Taking a little break · Sold out</div><?php endif; ?></div></article><?php endforeach; ?></div><?php if (!$items): ?><div class="empty panel"><h2>No matches this time.</h2><p>Try another search or browse the full menu.</p><a class="button" href="<?= e(url('menu')) ?>">See the full menu</a></div><?php endif; ?>
        <p class="menu-footnote">Made fresh in a shared kitchen. Please discuss allergies with café staff before ordering.</p>
    <?php break;
    case 'login': case 'register': $register = $page === 'register'; ?>
        <section class="auth-layout"><div class="auth-intro"><span class="eyebrow">THERE’S A PLACE FOR YOU HERE</span><h1><?= $register?'Good days.<br>Great company.':'Your usual<br>is waiting.' ?></h1><p>One account for your coffee runs, catch-ups and everything in between.</p><div class="auth-flower" aria-hidden="true">✳</div><span>SMALL CAFÉ. BIG WELCOME.</span></div><div class="auth-form"><span class="eyebrow">FOLKS & CO.</span><h2><?= $register?'Join the table.':'Welcome back.' ?></h2><p><?= $register?'Create an account to place and track your orders.':'Sign in to order ahead or manage the café.' ?></p><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="<?= $page ?>"><?php if ($register): ?><label>Your name<input name="name" autocomplete="name" maxlength="80" required></label><?php endif; ?><label>Email address<input name="email" type="email" autocomplete="email" maxlength="190" required></label><label>Password<input name="password" type="password" autocomplete="<?= $register?'new-password':'current-password' ?>" minlength="<?= $register?'10':'1' ?>" maxlength="72" required></label><?php if ($register): ?><small>Use 10–72 characters. A longer, unique password is best.</small><label class="checkbox"><input name="privacy" type="checkbox" value="yes" required><span>I have read the <a href="<?= e(url('privacy')) ?>">privacy notice</a>.</span></label><?php endif; ?><button class="button full"><?= $register?'Create account':'Sign in' ?> <span aria-hidden="true">↗</span></button></form><p class="auth-switch"><?= $register?'Already one of the folks?':'New around here?' ?> <a href="<?= e(url($register?'login':'register')) ?>"><?= $register?'Sign in':'Create an account' ?></a></p></div></section>
    <?php break;
    case 'cart':
        $lines = cart_details();
        heading('A LITTLE OF WHAT YOU LOVE','Your bag.','One step closer to your next good coffee break.');
        if (!$lines) { empty_bag(); break; }
        $total = array_sum(array_column($lines,'subtotal')); ?>
        <div class="checkout-layout"><div class="cart-lines"><?php foreach ($lines as $line): ?><article class="cart-line"><?php artwork($line['item'],'thumbnail'); ?><div class="cart-line-info"><h2><?= e($line['item']['name']) ?></h2><p><?= money((int)$line['item']['price_cents']) ?> each<?= !$line['item']['available']?' · Currently sold out':'' ?></p><?php if ($line['recipient']): ?><small>For <?= e($line['recipient']) ?></small><?php endif; ?><?php if ($line['instructions']): ?><small><?= e($line['instructions']) ?></small><?php endif; ?><div class="cart-controls"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="update_cart"><input type="hidden" name="key" value="<?= e($line['key']) ?>"><label class="sr-only" for="cart-<?= e($line['key']) ?>">Quantity for <?= e($line['item']['name']) ?></label><input id="cart-<?= e($line['key']) ?>" type="number" name="quantity" value="<?= $line['quantity'] ?>" min="1" max="20" required><button class="text-button">Update</button></form><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="remove_cart"><input type="hidden" name="key" value="<?= e($line['key']) ?>"><button class="text-button muted">Remove</button></form></div></div><strong><?= money($line['subtotal']) ?></strong></article><?php endforeach; ?><a class="underlined" href="<?= e(url('menu')) ?>">← Add a little more</a></div><aside class="summary panel"><span class="eyebrow">THE GOOD STUFF</span><h2>Order summary</h2><div class="summary-row"><span><?= cart_count() ?> items</span><span><?= money($total) ?></span></div><div class="summary-row"><span>Collection</span><span>Free</span></div><div class="summary-row total"><span>Total <small>AUD</small></span><span><?= money($total) ?></span></div><a class="button full" href="<?= e(url($user?'checkout':'login')) ?>"><?= $user?'Continue to checkout':'Sign in to checkout' ?> ↗</a><small>Choose your collection time at checkout. Payments are simulated for this student project.</small></aside></div>
    <?php break;
    case 'checkout':
        $lines = cart_details(); if (!$lines) { empty_bag(); break; }
        $total = array_sum(array_column($lines,'subtotal'));
        $slots = pickup_options();
        $full = array_column(query('SELECT slot_at FROM pickup_slots WHERE booked>=capacity')->fetchAll(),'slot_at');
        heading('YOUR NEXT GOOD MOMENT','Make it yours.','Choose a collection time. We’ll take it from here.'); ?>
        <form method="post" class="checkout-layout" data-checkout><?= csrf_field() ?><input type="hidden" name="action" value="checkout"><input type="hidden" name="checkout_key" value="<?= e(checkout_key()) ?>"><input type="hidden" name="expected_total" value="<?= $total ?>"><div class="form-sections"><section class="panel"><h2><span class="step-number">01</span> Your details</h2><div class="field-grid"><label>Collection name<input name="customer_name" value="<?= e($user['name']) ?>" autocomplete="name" maxlength="80" required></label><label>Phone number<input name="phone" type="tel" autocomplete="tel" maxlength="24" pattern="\+?[0-9 ()\-]{8,24}" required placeholder="04xx xxx xxx"></label></div><p class="field-help">Your phone number is only used if staff need to contact you about this order.</p><label>Group or team name <span class="optional">optional</span><input name="group_name" maxlength="80" placeholder="e.g. The Monday morning crew"></label></section><section class="panel"><h2><span class="step-number">02</span> Make a little time</h2><label>Collection time<select name="pickup_at" required><option value="">Choose a time</option><?php foreach ($slots as $value=>$label): if (in_array($value,$full,true)) continue; ?><option value="<?= e($value) ?>"><?= e($label) ?></option><?php endforeach; ?></select></label><small>Times are local to Canberra / Sydney. Daily 7 am–4 pm; last collection at 3:45 pm.</small><label>Anything we should know? <span class="optional">optional</span><textarea name="notes" rows="3" maxlength="500" placeholder="A note for our team"></textarea></label></section><section class="panel"><h2><span class="step-number">03</span> Demonstration payment</h2><p>This is a student project. No money is charged and no card details are needed.</p><label>Payment outcome<select name="payment_result" required><option value="approved">Approve simulated payment</option><option value="declined">Decline simulated payment (test)</option></select></label><label class="checkbox"><input type="checkbox" name="payment_consent" value="yes" required><span>I understand this payment is simulated.</span></label></section></div><aside class="summary panel"><span class="eyebrow">YOUR LITTLE PICK-ME-UP</span><h2>Order summary</h2><?php foreach ($lines as $line): ?><div class="summary-row"><span><?= $line['quantity'] ?> × <?= e($line['item']['name']) ?><?php if ($line['recipient']): ?><small>For <?= e($line['recipient']) ?></small><?php endif; ?></span><span><?= money($line['subtotal']) ?></span></div><?php endforeach; ?><div class="summary-row total"><span>Total <small>AUD</small></span><span><?= money($total) ?></span></div><button class="button full" data-submit>Place demo order ↗</button><a class="edit-bag" href="<?= e(url('cart')) ?>">Edit your bag</a><small>Menu prices and collection availability are confirmed when you place the order.</small></aside></form>
    <?php break;
    case 'confirmation': case 'track':
        $ref = is_string($_GET['ref'] ?? null) ? $_GET['ref'] : '';
        $order = order_for_user($ref,$user);
        $items = query('SELECT * FROM order_items WHERE order_id=?', [$order['id']])->fetchAll();
        $events = query('SELECT status,created_at FROM order_events WHERE order_id=? ORDER BY id', [$order['id']])->fetchAll();
        heading($page==='confirmation'?'THANK YOU, '.strtoupper($order['customer_name']):'FROM OUR COUNTER TO YOU',$page==='confirmation'?'A good choice. A great day.':'Your order, in the making.','Order '.$order['reference']); ?>
        <div class="checkout-layout"><div><section class="panel order-progress"><div class="section-heading"><h2><?= e(status_label($order['status'])) ?></h2><a class="underlined" href="<?= e(url('track',['ref'=>$ref])) ?>">Refresh status ↻</a></div><p><?= e(match($order['status']) {'received'=>'Your order is in. Our team will get started soon.','preparing'=>'A little care, a little craft. We’re preparing your order.','ready'=>'All ready! Show your order number at the counter.','collected'=>'Thanks for stopping by. See you next time.','cancelled'=>'This order was cancelled. The simulated payment has been refunded.'}) ?></p><ol class="progress-track"><?php foreach (['received','preparing','ready','collected'] as $step): ?><li class="<?= in_array($step,array_column($events,'status'),true)?'done':'' ?>"><span></span><?= e(status_label($step)) ?></li><?php endforeach; ?></ol><div class="pickup-info"><span>YOUR COLLECTION TIME</span><strong><?= e((new DateTimeImmutable($order['pickup_at']))->format('D j M · g:i a')) ?></strong><p>Collect at the café counter · Canberra / Sydney time</p></div></section><section class="panel"><h2>A little receipt</h2><?php foreach ($items as $item): ?><div class="summary-row"><div><strong><?= $item['quantity'] ?> × <?= e($item['item_name']) ?></strong><?php if ($item['recipient']): ?><small>For <?= e($item['recipient']) ?></small><?php endif; ?><?php if ($item['instructions']): ?><small><?= e($item['instructions']) ?></small><?php endif; ?></div><span><?= money((int)$item['unit_price_cents']*(int)$item['quantity']) ?></span></div><?php endforeach; ?><div class="summary-row total"><span>Total</span><span><?= money((int)$order['total_cents']) ?></span></div><p><?= $order['payment_status']==='simulated_paid'?'Simulated payment approved':'Simulated payment refunded' ?> · No money charged</p><small><?= e($order['payment_reference']) ?></small></section></div><aside class="panel summary"><span class="eyebrow">THE DETAILS</span><h2><?= e($order['customer_name']) ?></h2><p><?= e($order['phone']) ?></p><?php if ($order['group_name']): ?><h3>For the crew</h3><p><?= e($order['group_name']) ?></p><?php endif; ?><?php if ($order['notes']): ?><h3>Your note</h3><p><?= e($order['notes']) ?></p><?php endif; ?><h3>Order history</h3><ul class="event-list"><?php foreach ($events as $event): ?><li><?= e(status_label($event['status'])) ?><small><?= e((new DateTimeImmutable($event['created_at'],new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('Australia/Sydney'))->format('j M, g:i a')) ?></small></li><?php endforeach; ?></ul><a class="button secondary full" href="<?= e(url('menu')) ?>">Back to the menu ↗</a></aside></div>
    <?php break;
    case 'orders':
        heading('YOUR COFFEE BREAKS, COLLECTED','Your orders.','Track what’s brewing, or revisit an old favourite.');
        $orders = query('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC LIMIT 100', [$user['id']])->fetchAll();
        if (!$orders) { ?><div class="empty panel"><h2>Your first good choice is waiting.</h2><p>Once you place an order, you’ll find it here.</p><a class="button" href="<?= e(url('menu')) ?>">Explore the menu ↗</a></div><?php }
        foreach ($orders as $order): ?><a class="order-list-card" href="<?= e(url('track',['ref'=>$order['reference']])) ?>"><div><span class="eyebrow"><?= e($order['reference']) ?></span><h2><?= e((new DateTimeImmutable($order['pickup_at']))->format('D j M · g:i a')) ?></h2></div><span class="badge <?= e($order['status']) ?>"><?= e(status_label($order['status'])) ?></span><strong><?= money((int)$order['total_cents']) ?> ↗</strong></a><?php endforeach; break;
    case 'staff': render_staff(); break;
    case 'manage': render_manage(); break;
    case 'privacy':
        heading('A LITTLE TRANSPARENCY','Your details, treated with care.'); ?>
        <article class="prose panel"><h2>About this demonstration</h2><p>Folks & Co. is an ICT312 student café portal inspired by the supplied proposal. It is not the official Folks Gallery website. The menu, prices and branding are demonstration content.</p><h2>What we collect</h2><p>We store your account name, email and a password hash. An order records a collection name, phone number, items, preparation notes, collection time and simulated payment record. Do not enter sensitive personal information in notes. Use fictional details when demonstrating the system.</p><h2>How information is used</h2><p>Account details support sign-in and access to your own orders. Authorised café staff can read order information to prepare and hand over orders. The application does not include advertising trackers or send marketing messages.</p><h2>Payments</h2><p>All payments are simulated. This site does not ask for card numbers, expiry dates or security codes. An approved demonstration payment does not move money. Cancelling an order records a simulated refund.</p><h2>Cookies and account access</h2><p>An essential session cookie keeps you signed in and remembers your bag. Sign out when using a shared device. Ask the project operator to arrange account-data access or deletion; no self-service deletion feature is included.</p><h2>Retention</h2><p>The project operator should remove demonstration accounts and orders after assessment. For a real deployment, the operator must define retention periods, contact information and a lawful privacy policy before accepting real customer data.</p><h2>Allergies and availability</h2><p>Items are prepared in a shared kitchen. Speak to staff about allergies before placing an order. Preparation notes are requests and do not guarantee an allergen-free product.</p></article>
    <?php break;
    default: heading('404','That page has wandered off.'); ?><a class="button" href="<?= e(url('home')) ?>">Back home</a><?php
    }
}
function empty_bag(): void { ?><div class="empty panel"><span class="empty-symbol" aria-hidden="true">✳</span><h2>Something good belongs here.</h2><p>Your bag is empty. Let’s find your next favourite.</p><a class="button" href="<?= e(url('menu')) ?>">Explore the menu ↗</a></div><?php }
