CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(80) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(255) NOT NULL,
 role ENUM('customer','staff') NOT NULL DEFAULT 'customer',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS menu_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(100) NOT NULL,
 category VARCHAR(40) NOT NULL,
 description VARCHAR(500) NOT NULL,
 allergens VARCHAR(190) NOT NULL DEFAULT '',
 price_cents INT UNSIGNED NOT NULL,
 available TINYINT(1) NOT NULL DEFAULT 1,
 artwork VARCHAR(30) NOT NULL DEFAULT 'coffee'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pickup_slots (
 slot_at DATETIME PRIMARY KEY,
 capacity SMALLINT UNSIGNED NOT NULL DEFAULT 8,
 booked SMALLINT UNSIGNED NOT NULL DEFAULT 0,
 CHECK (booked <= capacity)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 reference VARCHAR(24) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NOT NULL,
 checkout_key CHAR(64) NOT NULL UNIQUE,
 customer_name VARCHAR(80) NOT NULL,
 phone VARCHAR(24) NOT NULL,
 pickup_at DATETIME NOT NULL,
 group_name VARCHAR(80) NOT NULL DEFAULT '',
 notes VARCHAR(500) NOT NULL DEFAULT '',
 total_cents INT UNSIGNED NOT NULL,
 status ENUM('received','preparing','ready','collected','cancelled') NOT NULL DEFAULT 'received',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id),
 FOREIGN KEY (pickup_at) REFERENCES pickup_slots(slot_at),
 INDEX idx_queue (status,pickup_at),
 INDEX idx_customer (user_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_items (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL,
 menu_item_id BIGINT UNSIGNED NOT NULL,
 item_name VARCHAR(100) NOT NULL,
 unit_price_cents INT UNSIGNED NOT NULL,
 quantity SMALLINT UNSIGNED NOT NULL,
 recipient VARCHAR(60) NOT NULL DEFAULT '',
 instructions VARCHAR(160) NOT NULL DEFAULT '',
 FOREIGN KEY (order_id) REFERENCES orders(id),
 FOREIGN KEY (menu_item_id) REFERENCES menu_items(id),
 CHECK (quantity BETWEEN 1 AND 20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL UNIQUE,
 amount_cents INT UNSIGNED NOT NULL,
 method VARCHAR(30) NOT NULL DEFAULT 'simulation',
 status ENUM('simulated_paid','simulated_refunded') NOT NULL DEFAULT 'simulated_paid',
 reference VARCHAR(40) NOT NULL UNIQUE,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (order_id) REFERENCES orders(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS order_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 order_id BIGINT UNSIGNED NOT NULL,
 actor_id BIGINT UNSIGNED NOT NULL,
 status VARCHAR(24) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (order_id) REFERENCES orders(id),
 FOREIGN KEY (actor_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_attempts (
 identity_hash CHAR(64) PRIMARY KEY,
 attempts INT UNSIGNED NOT NULL DEFAULT 0,
 window_started DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
